spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: dev
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: # jdbc:mysql://recruit.cgzz7jhrx4km.ap-northeast-2.rds.amazonaws.com:3306/juy5790
    username: juy5790
    password: juy57905797
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: local

  jpa:
    hibernate:
      ddl-auto: create-drop
