spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    open-in-view: true